### ISSUE TITLE
is struct tag missed?

### ISSUE THREAD

**Issue by hhrhhr** [Rseding91/Factorio-Lua#2]
https://github.com/Rseding91/Factorio-Lua/blob/31cf6fbe8b8550b1a8431649c4055736c605fd45/src/lobject.h#L446-L451

clang say:

> lobject.h:449:3: error: must use 'struct' tag to refer to type 'Node'
> lobject.h:450:3: error: must use 'struct' tag to refer to type 'Node'

Or are you not using a C compiler?

**Comment by Rseding91** [comment]
We don't compile Lua as C, we compile it as C++.
