### ISSUE TITLE
Impossible to compile with msvc, gcc, or mingw

### ISSUE THREAD

**Issue by notnotmelon** [Rseding91/Factorio-Lua#4]
This repo fails to compile on all tested windows c++ compilers. It fails due to a division by 0 error in `lmathlib.c`.

I was only able to successfully compile this repo after making the following adjustment:
https://github.com/factorio-rivets/Factorio-Lua/commit/b3f833cb99fb24ea6ba254f11ceabd7e458db77d

**Comment by Rseding91** [comment]
https://github.com/factorio-rivets/Factorio-Lua/commit/b3f833cb99fb24ea6ba254f11ceabd7e458db77d#diff-2918390f539d9896412ca17bb2ad831627cd1ee1f9e47a67bbbb0fef2839ad8fL32
